---
apiVersion: contivpp.io/v1
kind: ExternalInterface
metadata:
  name: vlan-200
spec:
  type: L2
  network: l2net
  nodes:
    - node: k8s-master
      vppInterfaceName: GigabitEthernet0/a/0
      VLAN: 200
